name: Scrape News Sites

on:
  # Run automatically every 6 hours
  schedule:
    - cron: '0 */6 * * *'
  # Allow manual running
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies from requirements.txt
        run: pip install -r requirements.txt

      - name: Run Scrapy spider
        # This requires your Scrapy project to be set up correctly
        # and that the spider's name is 'news_aggregator'
        run: scrapy crawl news_aggregator

      - name: Commit and push results
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update news articles"
          file_pattern: "*.json"
