name: Market Analysis

on:
  schedule:
    # Runs at 08:00 UTC (11:00 AM Baghdad time)
    - cron: '0 8 * * *'
  workflow_dispatch: # Allows manual running

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v3

      - name: Setup Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Required Libraries
        run: |
          python -m pip install --upgrade pip
          pip install numpy==1.26.4 pandas==2.2.2 pandas-ta yfinance requests newspaper3k

      - name: Run Gold Analysis Script
        run: python gold_analyzer.py

      - name: Run VIX Analysis Script
        run: python get_vix.py

      - name: Run Yields Analysis Script
        run: python get_yields.py

      - name: Run News Scraper Script
        run: python get_news.py

      - name: Save and Update Analysis Files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated analysis data update"
          file_pattern: "*.json" # This will now commit all .json files
